#!/bin/bash

ctr image pull $VCONTAINER_REGISTRY/hyperkube:v1.28.2
ctr image pull $VCONTAINER_REGISTRY/hyperkube:v1.27.6
ctr image pull $VCONTAINER_REGISTRY/hyperkube:v1.26.9
ctr image pull $VCONTAINER_REGISTRY/hyperkube:v1.25.14
ctr image pull $VCONTAINER_REGISTRY/hyperkube:v1.24.17
ctr image pull $VCONTAINER_REGISTRY/etcd:v3.5.9
ctr image pull $VCONTAINER_REGISTRY/heat-container-agent:v11.7.0
ctr image pull $VCONTAINER_REGISTRY/pause:3.1

ctr image tag $VCONTAINER_REGISTRY/hyperkube:v1.28.2 hyperkube:v1.28
ctr image label hyperkube:v1.28 "tag=v1.28.2"

ctr image tag $VCONTAINER_REGISTRY/hyperkube:v1.27.6 hyperkube:v1.27
ctr image label hyperkube:v1.27 "tag=v1.27.6"

ctr image tag $VCONTAINER_REGISTRY/hyperkube:v1.26.9 hyperkube:v1.26
ctr image label hyperkube:v1.26 "tag=v1.26.9"

ctr image tag $VCONTAINER_REGISTRY/hyperkube:v1.25.14 hyperkube:v1.25
ctr image label hyperkube:v1.25 "tag=v1.25.14"

ctr image tag $VCONTAINER_REGISTRY/hyperkube:v1.24.17 hyperkube:v1.24
ctr image label hyperkube:v1.24 "tag=v1.24.17"

ctr image tag $VCONTAINER_REGISTRY/etcd:v3.5.9 etcd:stable
ctr image label etcd:stable "tag=v3.5.9"

ctr image tag $VCONTAINER_REGISTRY/heat-container-agent:v11.7.0 heat-container-agent:stable
ctr image label heat-container-agent:stable "tag=v11.7.0"

ctr image tag $VCONTAINER_REGISTRY/pause:3.1 pause:stable
ctr image label pause:stable "tag=3.1"
