#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
  set -x
fi

set -eu
set -o pipefail

[ -n "$ARCH" ]
[ -n "$TARGET_ROOT" ]

# only support x86_64
if [ 'amd64' = "$ARCH" ] ; then
  ARCH="x86_64"
fi

DIB_LOCAL_IMAGE=${DIB_LOCAL_IMAGE:-""}
BASE_IMAGE_TAR=${BASE_IMAGE_TAR:-""}
IMAGE_LOCATION=${IMAGE_LOCATION:-""}
CACHED_IMAGE=${CACHED_IMAGE:-""}
BASE_IMAGE_FILE=${BASE_IMAGE_FILE:-""}

if [ -n "$DIB_LOCAL_IMAGE" ]; then
  IMAGE_LOCATION=$DIB_LOCAL_IMAGE
  # No need to copy a local image into the cache directory, so just specify the cached path as the original path.
  CACHED_IMAGE=$IMAGE_LOCATION
  BASE_IMAGE_FILE=`basename $DIB_LOCAL_IMAGE`
  BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
else
  # note default DIB_RELEASE set in environment setup
  case ${ARCH} in
  x86_64)
    case ${DIB_RELEASE} in
    39)
      DIB_CLOUD_IMAGES=${DIB_CLOUD_IMAGES:-https://hcm03.vstorage.vngcloud.vn/v1/AUTH_f32042ce6374482ab375ddce2d4a6837/qcow2}
      BASE_IMAGE_FILE=${BASE_IMAGE_FILE:-fedora-coreos-39.20231119.3.0-openstack.x86_64.qcow2}
      BASE_IMAGE_TAR=fedora-coreos-39.20231119.3.0-openstack.x86_64.tgz
      IMAGE_LOCATION=$DIB_CLOUD_IMAGES/$BASE_IMAGE_FILE
      CACHED_IMAGE=$DIB_IMAGE_CACHE/$BASE_IMAGE_FILE
      ;;
    *)
      DIB_CLOUD_IMAGES=${DIB_CLOUD_IMAGES:-https://hcm03.vstorage.vngcloud.vn/v1/AUTH_f32042ce6374482ab375ddce2d4a6837/qcow2}
      BASE_IMAGE_FILE=${BASE_IMAGE_FILE:-fedora-coreos-39.20231119.3.0-openstack.x86_64.qcow2}
      BASE_IMAGE_TAR=fedora-coreos-39.20231119.3.0-openstack.x86_64.tgz
      IMAGE_LOCATION=$DIB_CLOUD_IMAGES/$BASE_IMAGE_FILE
      CACHED_IMAGE=$DIB_IMAGE_CACHE/$BASE_IMAGE_FILE
      ;;
    esac
    ;;
  *)
    echo "[ERROR] Unknown ARCH: ${ARCH}"
    exit 1
    ;;
  esac
fi

$TMP_HOOKS_PATH/bin/extract-image $BASE_IMAGE_FILE $BASE_IMAGE_TAR $IMAGE_LOCATION $CACHED_IMAGE
