#!/bin/bash

########################################################################################################################
# Author: Cuong. Duong Manh <cuongdm8499@gmail.com>
# Description:
#    - Configure the environment variables to install cri-containerd-cni
#    - Currently, I use containerd version of 1.7.1 as default
########################################################################################################################

# Create the containerd tmp directory
_CONTAINERD_TMP="/tmp/containerd"
mkdir -p ${_CONTAINERD_TMP}

# Download the containerd tarball
i=0
until curl -o "${_CONTAINERD_TMP}/cri-containerd.tar.gz" -L "${CONTAINERD_TARBALL_URL}"; do
  i=$((i + 1))
  [ $i -lt 5 ] || break
  sleep 5
done

# Verify the checksum
if ! echo "${CONTAINERD_TARBALL_SHA256} /srv/magnum/cri-containerd.tar.gz" | sha256sum -c -; then
  echo "[ERROR] cri-containerd.tar.gz computed checksum did NOT match, exiting."
  exit 1
fi

# Untar the tarball
tar xzvf /srv/magnum/cri-containerd.tar.gz -C / --no-same-owner --touch --no-same-permissions

# Reload the daemon and start containerd
systemctl daemon-reload
systemctl enable containerd
systemctl start containerd